clone:
  path: github.com/stayallive/plesk-php-api

cache:
  mount:
    - vendor

build:
  test-php70:
    image: tetraweb/php:7.0
    commands:
      - docker-php-ext-enable zip mbstring pcntl
      - php -v
      - composer self-update --no-progress
      - composer install --no-progress --no-scripts
      - sleep 15
      - php vendor/bin/phpunit --colors=never
    environment:
      - REMOTE_URL=https://127.0.0.1:8443
      - REMOTE_PASSWORD=changeme

services:
  plesk:
    image: plesk/plesk:17.0
