pipeline:
  test-php70:
    image: tetraweb/php:7.0
    commands:
      - docker-php-ext-enable zip mbstring pcntl
      - php -v
      - composer self-update --no-progress
      - composer install --no-progress --no-scripts
      - until $(curl --output /dev/null --silent --insecure --head --fail $REMOTE_URL); do echo "Waiting for Plesk to start..."; sleep 10; done
      - php vendor/bin/phpunit --colors=never
    environment:
      - REMOTE_URL=https://plesk:8443
      - REMOTE_PASSWORD=changeme

services:
  plesk:
    image: plesk/plesk:17.5
